"""
Django settings for laudario project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SESSION_COOKIE_AGE = 60 * 60 * 12
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/



#PRODUÇÃO
#with open('/home/arthur/vars/chave') as t:
#    SECRET_KEY = t.read().strip()

#TESTE
#Chave para TESTE
#SECRET_KEY = 'xgrcf3&7)5oi82y*ou)+f8c_q4xo!j8qc&(u8m2sw9t!(a=p6v'
with open('/Users/arthur/vars/chave') as t:
    SECRET_KEY = t.read().strip()




# TESTE APENAS!
DEBUG = True

#PRODUÇÃO
#DEBUG = False

ALLOWED_HOSTS = []

#PRODUÇÃO
#ALLOWED_HOSTS = ['masqs.com.br', 'www.masqs.com.br', '191.252.58.203:80',]




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'laudario.masks',
    'tinymce',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'laudario.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'laudario.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

#PRODUÇÃO
#with open('/home/arthur/vars/senha') as f:
#    SENHA = f.read().strip()

#TESTE
with open('/Users/arthur/vars/senha') as f:
    SENHA = f.read().strip()

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'laudario',
	'USER': 'laudariousr',

     #PODE USER 'piabinha123', se quiser, como valor de PASSWORD de teste
	'PASSWORD': SENHA,




	'HOST': 'localhost',

    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = False

USE_L10N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_URL = '/static/'

#PRODUÇÃO
#Run collectstatic para passar tudo de STATIC_URL na pasta do app
#para STATI_ROOT no servidor.
#STATIC_ROOT = '/var/www/'




#Settings for email verification na produção (usuário tem que clicar em link enviado no email para ativar.
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'localhost'
#EMAIL_PORT = 25
#EMAIL_HOST_USER = ''
#EMAIL_HOST_PASSWORD = ''
#EMAIL_USE_TLS = True
#DEFAULT_FROM_EMAIL = 'Masqs <contato@masqs.com.br>'

TINYMCE_JS_URL = os.path.join(STATIC_URL, "tinymce/js/tinymce/tinymce.min.js")

#Produção
#TINYMCE_JS_ROOT = os.path.join(STATIC_ROOT, "tinymce/js/tinymce")

TINYMCE_DEFAULT_CONFIG = {
    'theme': "simple",
    'relative_urls': False}


#PRODUÇÃO APENAS
#CSRF_COOKIE_SECURE = True
#SESSION_COOKIE_SECURE = True