# Generated by Django 3.0.7 on 2020-06-12 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('initials', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mascara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('tecnica_header', models.CharField(max_length=50)),
                ('tecnica', models.CharField(max_length=500)),
                ('relatorio_header', models.CharField(max_length=500)),
                ('conclusao_header', models.CharField(max_length=50)),
                ('conclusao', models.CharField(max_length=100)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Especialidade')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Exame')),
            ],
        ),
        migrations.CreateModel(
            name='TopicoNormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=50)),
                ('relatorio', models.TextField(max_length=500)),
                ('mascara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Mascara')),
            ],
        ),
        migrations.CreateModel(
            name='TopicoAnormalBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('topico_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.TopicoNormal')),
            ],
        ),
        migrations.CreateModel(
            name='TopicoAnormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('relatorio', models.CharField(max_length=500)),
                ('conclusao', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_diagnostico', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masks.GrupoDiagnostico')),
                ('topico_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.TopicoNormal')),
            ],
        ),
    ]
