# Generated by Django 3.0.6 on 2020-05-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=25)),
                ('initials', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=25)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=25)),
                ('string_variable', models.CharField(max_length=25)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.System')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('technique_header', models.CharField(max_length=50)),
                ('technique', models.CharField(max_length=500)),
                ('report_header', models.CharField(max_length=500)),
                ('figado', models.TextField(default='')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Exam')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.System')),
            ],
        ),
    ]
