# Generated by Django 3.0.6 on 2020-06-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicoanormal',
            name='grupo_diagnostico',
        ),
        migrations.DeleteModel(
            name='GrupoDiagnostico',
        ),
    ]
