# Generated by Django 3.0.6 on 2020-05-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description_l', models.CharField(max_length=50)),
                ('description_s', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description_l', models.CharField(max_length=50)),
                ('description_s', models.CharField(max_length=25)),
                ('especialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Especialty')),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description_l', models.CharField(max_length=50)),
                ('description_s', models.CharField(max_length=25)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.System')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_mascara', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('tecnica_header', models.CharField(max_length=50)),
                ('tecnica', models.CharField(max_length=500)),
                ('relatorio_header', models.CharField(max_length=500)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Exam')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.System')),
            ],
        ),
    ]
