# Generated by Django 3.0.6 on 2020-06-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='conclusao_header',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
