# Generated by Django 3.0.6 on 2020-06-02 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascara',
            name='sistema',
        ),
        migrations.AddField(
            model_name='mascara',
            name='especialidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='masks.Especialidade'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sistema',
        ),
    ]
