# Generated by Django 3.0.6 on 2020-05-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0002_auto_20200529_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialty',
            new_name='Specialty',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='especialty',
            new_name='specialty',
        ),
    ]
