# Generated by Django 3.0.7 on 2020-06-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0002_auto_20200612_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeDaVariavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_variavel', models.CharField(max_length=50)),
                ('nome_amigavel', models.CharField(max_length=50)),
                ('unidade_medida', models.CharField(max_length=10)),
            ],
        ),
    ]
