# Generated by Django 3.0.6 on 2020-06-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0002_mascara_conclusao_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicoanormal',
            name='descricao',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicoanormal',
            name='javascript',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicoanormal',
            name='nome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
