# Generated by Django 3.0.6 on 2020-06-02 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0002_auto_20200602_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='conclusao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='TopicoLaudo',
            new_name='TopicoNormal',
        ),
        migrations.CreateModel(
            name='TopicoAnormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio', models.CharField(max_length=500)),
                ('conclusao', models.CharField(max_length=100)),
                ('topico_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.TopicoNormal')),
            ],
        ),
    ]
