# Generated by Django 3.0.6 on 2020-06-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0003_auto_20200603_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicoanormal',
            name='javascript',
        ),
        migrations.AddField(
            model_name='topicoanormal',
            name='template_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
