# Generated by Django 3.0.6 on 2020-06-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0003_auto_20200602_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='template_name',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
