# Generated by Django 3.0.7 on 2020-06-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0003_nomedavariavel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NomeDaVariavel',
            new_name='Variavel',
        ),
    ]
