# Generated by Django 3.0.6 on 2020-05-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0003_auto_20200529_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='description_l',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='description_s',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='mask',
            old_name='nome_mascara',
            new_name='mask_name',
        ),
        migrations.RenameField(
            model_name='mask',
            old_name='relatorio_header',
            new_name='report_header',
        ),
        migrations.RenameField(
            model_name='mask',
            old_name='tecnica',
            new_name='technique',
        ),
        migrations.RenameField(
            model_name='mask',
            old_name='tecnica_header',
            new_name='technique_header',
        ),
        migrations.RenameField(
            model_name='mask',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='organ',
            old_name='description_l',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='organ',
            old_name='description_s',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='specialty',
            old_name='description_l',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='specialty',
            old_name='description_s',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='description_l',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='description_s',
            new_name='short_description',
        ),
    ]
