# Generated by Django 3.0.7 on 2020-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0004_auto_20200613_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variavel',
            name='nome_amigavel',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='variavel',
            name='nome_da_variavel',
            field=models.CharField(max_length=100),
        ),
    ]
