# Generated by Django 3.0.6 on 2020-06-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0004_auto_20200604_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascara',
            name='template_name',
        ),
    ]
