# Generated by Django 3.0.6 on 2020-05-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0005_auto_20200529_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='string_variable',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
