# Generated by Django 3.0.6 on 2020-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0006_organ_string_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='figado',
            field=models.TextField(default=''),
        ),
    ]
