# Generated by Django 3.0.6 on 2020-06-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0006_remove_topicoanormal_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicoanormal',
            name='template_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
