# Generated by Django 3.0.7 on 2020-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0007_variavel_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascara',
            name='conclusao',
            field=models.CharField(max_length=500),
        ),
    ]
