# Generated by Django 3.0.6 on 2020-06-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0007_topicoanormal_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicoanormal',
            name='template_name',
        ),
        migrations.CreateModel(
            name='TopicoAnormalBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('topico_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.TopicoNormal')),
            ],
        ),
    ]
