# Generated by Django 3.0.7 on 2020-06-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0008_auto_20200609_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiconormal',
            name='relatorio',
            field=models.TextField(max_length=500),
        ),
    ]
