# Generated by Django 3.0.7 on 2020-06-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0009_auto_20200610_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicoanormal',
            name='conclusao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
