# Generated by Django 3.0.7 on 2020-07-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0009_auto_20200720_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='frequencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mascara',
            name='popularidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mascara',
            name='publica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topicoanormal',
            name='frequencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topicoanormal',
            name='popularidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topicoanormal',
            name='publica',
            field=models.BooleanField(default=True),
        ),
    ]
