# Generated by Django 3.0.7 on 2020-08-25 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0014_auto_20200825_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascara',
            name='ultima_vez_usado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
