# Generated by Django 3.0.7 on 2020-08-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0015_auto_20200825_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fonte',
            field=models.CharField(default='Arial, Helvetica, sans-serif', max_length=100),
            preserve_default=False,
        ),
    ]
