# Generated by Django 3.0.7 on 2020-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0016_profile_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cor_topicos',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fonte',
            field=models.CharField(default='Arial, Helvetica, sans-serif', max_length=100),
        ),
    ]
