# Generated by Django 3.0.7 on 2020-08-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0017_auto_20200826_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tamanho_fonte',
            field=models.CharField(default='1em', max_length=20),
        ),
    ]
