# Generated by Django 3.0.7 on 2020-08-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0019_auto_20200827_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alinhamento_topicos',
            field=models.CharField(default='left', max_length=20),
        ),
    ]
