# Generated by Django 3.0.7 on 2020-08-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0020_profile_alinhamento_topicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tamanho_titulo',
            field=models.CharField(default='2em', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='tamanho_topicos',
            field=models.CharField(default='1.7em', max_length=20),
        ),
    ]
