# Generated by Django 3.0.7 on 2020-08-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0021_auto_20200827_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='info_adicional',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='tamanho_fonte',
            field=models.CharField(default='16px', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tamanho_titulo',
            field=models.CharField(default='32px', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tamanho_topicos',
            field=models.CharField(default='28px', max_length=20),
        ),
        migrations.AlterField(
            model_name='topicoanormal',
            name='relatorio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='topiconormal',
            name='relatorio',
            field=models.TextField(max_length=1000),
        ),
    ]
