# Generated by Django 3.0.7 on 2020-08-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0023_profile_espacamento_topicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='altura_linha',
            field=models.CharField(default='100%', max_length=20),
        ),
    ]
