# Generated by Django 3.0.7 on 2020-09-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0024_profile_altura_linha'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='margem_cabecalho',
            field=models.CharField(default='20px', max_length=20),
        ),
    ]
