# Generated by Django 3.0.7 on 2020-09-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0026_auto_20200910_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='indicacoes',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascara',
            name='indicacoes_header',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variavel',
            name='nome_amigavel',
            field=models.CharField(max_length=200),
        ),
    ]
