# Generated by Django 3.0.7 on 2020-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0027_auto_20200917_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='capitalizacao',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
