# Generated by Django 3.0.7 on 2020-09-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0028_profile_capitalizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variavel',
            name='nome_amigavel',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='variavel',
            name='nome_da_variavel',
            field=models.CharField(max_length=1000),
        ),
    ]
