# Generated by Django 3.0.7 on 2020-09-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0029_auto_20200919_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiconormal',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
