# Generated by Django 3.0.7 on 2020-10-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0031_auto_20201001_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='variavel',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
