# Generated by Django 3.0.7 on 2020-10-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0032_variavel_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascara',
            name='conclusao',
            field=models.CharField(max_length=3000),
        ),
    ]
