# Generated by Django 3.0.7 on 2021-04-11 20:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0034_auto_20201015_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='data_criada',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 20, 18, 16, 121034, tzinfo=utc)),
        ),
    ]
