# Generated by Django 3.0.7 on 2021-04-11 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0035_mascara_data_criada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascara',
            name='data_criada',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 20, 20, 22, 875269, tzinfo=utc)),
        ),
    ]
