# Generated by Django 3.0.7 on 2021-04-11 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0036_auto_20210411_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicoanormal',
            name='data_criada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mascara',
            name='data_criada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
