# Generated by Django 3.0.7 on 2021-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0037_auto_20210411_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mascara_topicos',
            field=models.BooleanField(default=False),
        ),
    ]
