# Generated by Django 3.0.7 on 2021-04-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0038_profile_mascara_topicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quadro_mais',
            field=models.BooleanField(default=False),
        ),
    ]
