# Generated by Django 3.0.7 on 2022-01-03 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0039_profile_quadro_mais'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vencimento_premium',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
