# Generated by Django 3.0.7 on 2022-01-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0040_profile_vencimento_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
