# Generated by Django 3.1.14 on 2022-01-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0041_profile_preference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.CharField(max_length=4000)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='topicoanormal',
            name='relatorio',
            field=models.CharField(max_length=4000),
        ),
    ]
