# Generated by Django 3.1.14 on 2022-01-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0044_mensagem_data_enviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='capitalizacao_topicos',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
