# Generated by Django 3.1.14 on 2022-01-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0045_profile_capitalizacao_topicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='mascara_topicos',
            field=models.BooleanField(default=False),
        ),
    ]
