# Generated by Django 3.1.14 on 2022-02-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0046_mascara_mascara_topicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiconormal',
            name='orgao',
            field=models.CharField(max_length=100),
        ),
    ]
